name: Build + deploy to GitHub Pages
on: { push: { branches: [ main ] } }
jobs:
  build:
    name: Build + deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: { persist-credentials: false }
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - run: echo 'node_modules/.bin' >> $GITHUB_PATH
      - run: yarn
      - run: next build
      - run: next export
      - run: touch out/.nojekyll
      - name: Deploy to GH Page
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: ghp
          folder: out
